---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/user/{user_id}/posts":
    get:
      summary: Retrieve all the users
      tags:
      - Blogs
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: blog found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
